version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: wave_opt_postgres
    environment:
      POSTGRES_DB: warehouse_opt
      POSTGRES_USER: wave_user
      POSTGRES_PASSWORD: wave_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wave_user -d warehouse_opt"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: wave_opt_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@waveopt.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: 